apiVersion: v1
kind: Secret
metadata:
  name: crossplane-secrets
  namespace: crossplane-system
type: Opaque
stringData:
  linodeRootPass: "YOUR-SECURE-ROOT-PASSWORD-HERE"
  linodeCredentials: |
    {
      "token": "YOUR-SECURE-PERSONAL-ACCESS-TOKEN-HERE"
    }    
---
apiVersion: linode.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: crossplane-secrets
      namespace: crossplane-system
      key: linodeCredentials
---
apiVersion: instance.linode.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    image: linode/ubuntu20.04
    type: g6-nanode-1
    label: crossplane-deployment-example
    region: us-southeast
    rootPassSecretRef:
      key: linodeRootPass
      name: crossplane-secrets
      namespace: crossplane-system
